// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjjflvdxomgyxqgdsewk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqamZsdmR4b21neXhxZ2RzZXdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NjIwNDMsImV4cCI6MjA3MDEzODA0M30.0Au4S3TF3Twykjh4UPkjqdkI-hfkSPAyArWDh2NLqiI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});