// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cirkxemaeahswdqmwagl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpcmt4ZW1hZWFoc3dkcW13YWdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMjA4NTQsImV4cCI6MjA2OTg5Njg1NH0.0yw5tsxYnrB4BhO8SZ87jbbfZy5aB8141N_1A7aJ-pc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});